### 1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

In [5]:
X = [[1,2,3],
    [3 ,5,6],
    [2 ,8,9]]
  
Y = [[5,9,1],
    [6,8,2],
    [3,2,4]]
 
res = np.array(X) + np.array(Y)
 
print(res)

[[ 6 11  4]
 [ 9 13  8]
 [ 5 10 13]]


### 2. Write a Python Program to Multiply Two Matrices?

In [6]:
X = [[1,2,3],
    [3 ,5,6],
    [2 ,8,9]]
  
Y = [[5,9,1],
    [6,8,2],
    [3,2,4]]
 
res = np.array(X) * np.array(Y)
 
print(res)

[[ 5 18  3]
 [18 40 12]
 [ 6 16 36]]


### 3. Write a Python Program to Transpose a Matrix?

In [16]:
A = np.array([[9, 1],[4, 2]])
T = A.transpose()
print(T)

[[9 4]
 [1 2]]



### 4. Write a Python Program to Sort Words in Alphabetic Order?


In [17]:
str = input("Enter a string: ")
 
words = str.split()

words.sort()

for word in words:
    print(word)

Enter a string: I love Python
I
Python
love


### 5. Write a Python Program to Remove Punctuation From a String?

In [20]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~''' 

my_str = input("Enter a string: ")

no_punct = ""
for char in my_str:
    if char not in punctuations:
        no_punct = no_punct + char

print(no_punct)

Enter a string: "Hello!!!, he said ---and went."
Hello he said and went
